"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/veo/tasks"

ENDPOINTS = {
    "veo_generate_video": {
        "method": "POST",
        "path": "/veo/videos",
        "operation": "generate",
        "schema": {
            "type": "object",
            "required": ["action"],
            "properties": {
                "model": {
                    "enum": ["veo3", "veo3-fast", "veo31-fast", "veo31", "veo31-fast-ingredients"],
                    "type": "string",
                },
                "resolution": {"enum": ["4k", "1080p", "gif"], "type": "string"},
                "action": {
                    "enum": ["text2video", "image2video", "ingredients2video", "get1080p"],
                    "type": "string",
                },
                "prompt": {"type": "string"},
                "video_id": {"type": "string"},
                "translation": {"type": "boolean"},
                "aspect_ratio": {"enum": ["16:9", "9:16"], "type": "string"},
                "image_urls": {"type": "array", "items": {"type": "string"}},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "model": {
                "enum": ["veo3", "veo3-fast", "veo31-fast", "veo31", "veo31-fast-ingredients"],
                "type": "string",
            },
            "resolution": {"enum": ["4k", "1080p", "gif"], "type": "string"},
            "action": {
                "enum": ["text2video", "image2video", "ingredients2video", "get1080p"],
                "type": "string",
            },
            "prompt": {"type": "string"},
            "video_id": {"type": "string"},
            "translation": {"type": "boolean"},
            "aspect_ratio": {"enum": ["16:9", "9:16"], "type": "string"},
            "image_urls": {"type": "array", "items": {"type": "string"}},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {"model": "veo31-fast", "action": "text2video", "aspect_ratio": "16:9"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "veo_extend_video": {
        "method": "POST",
        "path": "/veo/extend",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["video_id", "model"],
            "properties": {
                "video_id": {"type": "string"},
                "model": {"type": "string", "enum": ["veo31-fast", "veo31"]},
                "prompt": {"type": "string"},
                "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"]},
                "resolution": {"type": "string", "enum": ["720p", "1080p"]},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "video_id": {"type": "string"},
            "model": {"type": "string", "enum": ["veo31-fast", "veo31"]},
            "prompt": {"type": "string"},
            "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16"]},
            "resolution": {"type": "string", "enum": ["720p", "1080p"]},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "veo_edit_objects": {
        "method": "POST",
        "path": "/veo/objects",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["video_id", "action"],
            "properties": {
                "action": {"type": "string", "enum": ["insert", "remove"]},
                "video_id": {"type": "string"},
                "prompt": {"type": "string"},
                "image_mask": {"type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "action": {"type": "string", "enum": ["insert", "remove"]},
            "video_id": {"type": "string"},
            "prompt": {"type": "string"},
            "image_mask": {"type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "veo_reshoot_video": {
        "method": "POST",
        "path": "/veo/reshoot",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["video_id", "motion_type"],
            "properties": {
                "video_id": {"type": "string"},
                "motion_type": {
                    "type": "string",
                    "enum": [
                        "STATIONARY",
                        "STATIONARY_UP",
                        "STATIONARY_DOWN",
                        "STATIONARY_LEFT",
                        "STATIONARY_RIGHT",
                        "STATIONARY_DOLLY_IN_ZOOM_OUT",
                        "STATIONARY_DOLLY_OUT_ZOOM_IN",
                        "UP",
                        "DOWN",
                        "LEFT_TO_RIGHT",
                        "RIGHT_TO_LEFT",
                        "FORWARD",
                        "BACKWARD",
                        "DOLLY_IN_ZOOM_OUT",
                        "DOLLY_OUT_ZOOM_IN",
                    ],
                },
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "video_id": {"type": "string"},
            "motion_type": {
                "type": "string",
                "enum": [
                    "STATIONARY",
                    "STATIONARY_UP",
                    "STATIONARY_DOWN",
                    "STATIONARY_LEFT",
                    "STATIONARY_RIGHT",
                    "STATIONARY_DOLLY_IN_ZOOM_OUT",
                    "STATIONARY_DOLLY_OUT_ZOOM_IN",
                    "UP",
                    "DOWN",
                    "LEFT_TO_RIGHT",
                    "RIGHT_TO_LEFT",
                    "FORWARD",
                    "BACKWARD",
                    "DOLLY_IN_ZOOM_OUT",
                    "DOLLY_OUT_ZOOM_IN",
                ],
            },
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "veo_upsample_video": {
        "method": "POST",
        "path": "/veo/upsample",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["video_id", "action"],
            "properties": {
                "action": {"type": "string", "enum": ["1080p", "4k", "gif"]},
                "video_id": {"type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "action": {"type": "string", "enum": ["1080p", "4k", "gif"]},
            "video_id": {"type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "veo_task_retrieve": {
        "method": "POST",
        "path": "/veo/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
                "trace_id": {"type": "string", "format": "uuid"},
                "trace_ids": {"type": "array", "items": {"type": "string", "format": "uuid"}},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
                "type": {"type": "string"},
                "created_at_min": {"type": "number", "format": "double"},
                "created_at_max": {"type": "number", "format": "double"},
            },
            "required": ["action"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            "trace_id": {"type": "string", "format": "uuid"},
            "trace_ids": {"type": "array", "items": {"type": "string", "format": "uuid"}},
            "offset": {"type": "integer", "minimum": 0},
            "limit": {"type": "integer", "minimum": 1},
            "type": {"type": "string"},
            "created_at_min": {"type": "number", "format": "double"},
            "created_at_max": {"type": "number", "format": "double"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "veo_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/veo/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
                "trace_id": {"type": "string", "format": "uuid"},
                "trace_ids": {"type": "array", "items": {"type": "string", "format": "uuid"}},
                "offset": {"type": "integer", "minimum": 0},
                "limit": {"type": "integer", "minimum": 1},
                "type": {"type": "string"},
                "created_at_min": {"type": "number", "format": "double"},
                "created_at_max": {"type": "number", "format": "double"},
            },
            "required": ["action"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            "trace_id": {"type": "string", "format": "uuid"},
            "trace_ids": {"type": "array", "items": {"type": "string", "format": "uuid"}},
            "offset": {"type": "integer", "minimum": 0},
            "limit": {"type": "integer", "minimum": 1},
            "type": {"type": "string"},
            "created_at_min": {"type": "number", "format": "double"},
            "created_at_max": {"type": "number", "format": "double"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
